#!/bin/sh

# 创建备份目录
mkdir -p /etc/AutoUpdateHosts
chmod 755 /etc/AutoUpdateHosts

# 确保配置存在
uci -q batch <<-EOF >/dev/null
    delete autoupdatehosts.@config[-1]
    add autoupdatehosts config
    set autoupdatehosts.@config[-1].enabled='0'
    set autoupdatehosts.@config[-1].urls=''
    set autoupdatehosts.@config[-1].schedule=''
    set autoupdatehosts.@config[-1].backup_path='/etc/AutoUpdateHosts/hosts.bak'
    commit autoupdatehosts
EOF

exit 0 