name: Build and Release

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

jobs:
  build:
    name: Build OpenWrt LuCI App
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install Build Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential libncurses5-dev libncursesw5-dev \
          zlib1g-dev gawk git gettext libssl-dev xsltproc rsync unzip

      - name: Setup OpenWrt SDK
        run: |
          wget https://downloads.openwrt.org/releases/22.03.5/targets/x86/64/openwrt-sdk-22.03.5-x86-64_gcc-11.2.0_musl.Linux-x86_64.tar.xz
          tar xJf openwrt-sdk-*.tar.xz
          mv openwrt-sdk-* sdk
          
      - name: Setup SDK Environment
        run: |
          cd sdk
          # 更新 feeds
          ./scripts/feeds update -a
          ./scripts/feeds install -a
          # 链接应用到 SDK package 目录
          ln -sf $GITHUB_WORKSPACE package/luci-app-autoupdatehosts
          
      - name: Build Package
        run: |
          cd sdk
          make defconfig
          make package/luci-app-autoupdatehosts/compile V=s

      - name: Organize IPK files
        run: |
          mkdir -p release
          find sdk/bin/packages/*/base/ -name "luci-app-autoupdatehosts*.ipk" -exec cp {} release/ \;
          find sdk/bin/packages/*/base/ -name "luci-i18n-autoupdatehosts*.ipk" -exec cp {} release/ \;

      - name: Generate Release Notes
        run: |
          echo "### LuCI App AutoUpdateHosts Release" > release.txt
          echo "包含以下文件：" >> release.txt
          ls -1 release/ >> release.txt

      - name: Create Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: release/*
          body_path: release.txt
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}