name: Build and Release

on:
  push:
    tags:
      - "v*"
      - "t*"
      - "pre-release-*"
  workflow_dispatch:

# 添加权限配置
permissions:
  contents: write
  discussions: write

jobs:
  create_prerelease_tag:
    name: Create Pre-release Tag
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/t')
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Git
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'

      - name: Create Pre-release Tag
        run: |
          TIMESTAMP=$(date +%Y%m%d%H%M%S)
          NEW_TAG="pre-release-$TIMESTAMP"
          git tag $NEW_TAG
          git push origin $NEW_TAG
          echo "创建预发布标签: $NEW_TAG"

  build_and_release:
    name: Build and Release
    runs-on: ubuntu-latest
    # 只在收到 pre-release- 或 v 开头的标签时执行
    if: startsWith(github.ref, 'refs/tags/pre-release-') || startsWith(github.ref, 'refs/tags/v')
    steps:
      - name: Check Environment
        run: |
          if [ "${{ secrets.IS_GITHUB_RUN }}" != "true" ]; then
            echo "非github环境，终止执行"
            exit 1
          fi
          echo "github环境检查通过，继续执行"

      - name: Set Release Info
        id: release_info
        run: |
          TAG_NAME=${GITHUB_REF#refs/tags/}
          echo "RELEASE_VERSION=$TAG_NAME" >> $GITHUB_ENV
          if [[ $TAG_NAME == pre-release-* ]]; then
            echo "IS_PRERELEASE=true" >> $GITHUB_ENV
            echo "构建预发布版本: $TAG_NAME"
          else
            echo "IS_PRERELEASE=false" >> $GITHUB_ENV
            echo "构建正式版本: $TAG_NAME"
          fi

      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install Build Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential libncurses5-dev libncursesw5-dev \
          zlib1g-dev gawk git gettext libssl-dev xsltproc rsync unzip

      - name: Setup OpenWrt SDK
        run: |
          rm -rf sdk
          wget https://downloads.openwrt.org/releases/22.03.5/targets/x86/64/openwrt-sdk-22.03.5-x86-64_gcc-11.2.0_musl.Linux-x86_64.tar.xz
          tar xJf openwrt-sdk-*.tar.xz
          mv openwrt-sdk-22.03.5-x86-64_gcc-11.2.0_musl.Linux-x86_64 sdk
          
      - name: Setup SDK Environment
        run: |
          cd sdk
          ./scripts/feeds update -a
          ./scripts/feeds install -a
          ln -sf $GITHUB_WORKSPACE package/luci-app-autoupdatehosts
          
      - name: Build Package
        run: |
          cd sdk
          make defconfig
          make package/luci-app-autoupdatehosts/compile V=s

      - name: Organize IPK files
        run: |
          mkdir -p release
          find sdk/bin/packages/*/base/ -name "luci-app-autoupdatehosts*.ipk" -exec cp {} release/ \;
          find sdk/bin/packages/*/base/ -name "luci-i18n-autoupdatehosts*.ipk" -exec cp {} release/ \;

      - name: Generate Release Notes
        run: |
          echo "### LuCI App AutoUpdateHosts Release" > release.txt
          echo "包含以下文件：" >> release.txt
          ls -1 release/ >> release.txt

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: release/*
          body_path: release.txt
          prerelease: ${{ env.IS_PRERELEASE == 'true' }}
          tag_name: ${{ env.RELEASE_VERSION }}
          name: ${{ env.RELEASE_VERSION }}
          generate_release_notes: true
          fail_on_unmatched_files: false
          token: ${{ secrets.REPO_TOKEN }}